#!/usr/bin/env python3
"""Write the shared JIS-row to Unicode table the browser links into DROM.

The firmware has no codec library and no room for a general one: this runs
on the host, and the checked-in `browser/data/shiftjis.bin` is what
`include_bytes!` picks up. See `docs/plans/archive/BROWSER_UI_PLAN.md` for why the table
looks like this, and `browser/src/encoding.rs` for how it is read.

The source is CPython's `cp932`, not `shift_jis`. What calls itself
Shift_JIS on the web is Windows-31J in practice, and decoding it with the
narrower codec loses the NEC and IBM extension rows -- circled numbers,
Roman numerals, and the kanji variants that turn up in names. WHATWG's
encoding standard makes the same choice, mapping the `shift_jis` label onto
the Windows index.

EUC-JP plane 1 addresses the first 94 rows of the same table directly. This
project accepts the small CP932/JIS mapping differences because its legacy
decoders prioritize readable old pages over standards-perfect conversion.

The table is indexed by JIS row and cell (ku and ten), 1-based, which is
what the two-byte form decodes to:

Shift_JIS converts its bytes to a row and cell as follows:

    lead 0x81..=0x9F -> c1 = lead - 0x81
    lead 0xE0..=0xFC -> c1 = lead - 0xC1
    trail 0x40..=0x7E -> c2 = trail - 0x40
    trail 0x80..=0xFC -> c2 = trail - 0x41
    ku = c1 * 2 + (1 if c2 < 94 else 2)      ten = c2 % 94 + 1

`lead = 0xFC` gives ku 120, which is where `ROWS` comes from. Rows 95 and up
are the IBM extensions; keeping them in the same array is what makes the
extension free rather than a second table with a second lookup.

Single bytes are not in the table. ASCII is itself, 0xA1..=0xDF is halfwidth
katakana at a fixed offset, and everything else is invalid -- all three are
arithmetic in the decoder.
"""

from __future__ import annotations

import argparse
import struct
import sys
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPOSITORY = HERE.parent.parent
OUTPUT = REPOSITORY / "browser" / "data" / "shiftjis.bin"
REPORT = REPOSITORY / "browser" / "data" / "shiftjis.txt"

CODEC = "cp932"
MAGIC = b"T5S1"
FORMAT_VERSION = 1
HEADER_BYTES = 16
ROWS = 120
CELLS = 94
# Nothing maps to U+0000, so zero is free to mean "no such character".
UNMAPPED = 0


def encode(ku: int, ten: int) -> bytes:
    """The two Shift_JIS bytes for a 1-based row and cell.

    The inverse of the arithmetic in the module docstring, and written out
    rather than reusing the decoder's so that a mistake in one does not
    cancel a matching mistake in the other.
    """
    c1 = (ku - 1) // 2
    c2 = (ten - 1) + (0 if ku % 2 == 1 else CELLS)
    lead = c1 + 0x81 if c1 < 0x1F else c1 + 0xC1
    trail = c2 + 0x40 if c2 < 0x3F else c2 + 0x41
    return bytes((lead, trail))


def build() -> tuple[list[int], int, list[int]]:
    """The table, how many cells are filled, and the rows that have any."""
    table = [UNMAPPED] * (ROWS * CELLS)
    filled = 0
    rows: list[int] = []
    for ku in range(1, ROWS + 1):
        used = False
        for ten in range(1, CELLS + 1):
            try:
                text = encode(ku, ten).decode(CODEC)
            except UnicodeDecodeError:
                continue
            # Every cp932 cell that decodes at all decodes to one scalar in
            # the BMP. A second scalar would need a decoder that can emit
            # two characters for one cell, which this one deliberately
            # cannot -- so it is an error here rather than a surprise there.
            if len(text) != 1 or ord(text[0]) > 0xFFFF:
                raise SystemExit(f"ku {ku} ten {ten} decodes to {text!r}, which does not fit")
            table[(ku - 1) * CELLS + (ten - 1)] = ord(text[0])
            filled += 1
            used = True
        if used:
            rows.append(ku)
    return table, filled, rows


def serialize(table: list[int]) -> bytes:
    body = struct.pack(f"<{len(table)}H", *table)
    header = struct.pack(
        "<4sHHHHI",
        MAGIC,
        FORMAT_VERSION,
        ROWS,
        CELLS,
        0,  # reserved, so the CRC lands on a four-byte boundary
        zlib.crc32(body),
    )
    assert len(header) == HEADER_BYTES, len(header)
    return header + body


def write_report(payload: bytes, filled: int, rows: list[int]) -> str:
    spans: list[str] = []
    start = previous = rows[0]
    for row in rows[1:]:
        if row == previous + 1:
            previous = row
            continue
        spans.append(f"{start}-{previous}" if start != previous else f"{start}")
        start = previous = row
    spans.append(f"{start}-{previous}" if start != previous else f"{start}")
    return "\n".join(
        [
            "shiftjis.bin -- generated by tools/encoding/generate_shiftjis.py,",
            "do not hand-edit.",
            "",
            f"codec            {CODEC}",
            f"format version   {FORMAT_VERSION}",
            f"rows             {ROWS}",
            f"cells per row    {CELLS}",
            f"mapped cells     {filled} of {ROWS * CELLS}",
            f"rows in use      {' '.join(spans)}",
            f"bytes            {len(payload)}",
            f"crc32            {zlib.crc32(payload[HEADER_BYTES:]):08x}",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing if the checked-in file is out of date",
    )
    arguments = parser.parse_args()

    table, filled, rows = build()
    payload = serialize(table)
    report = write_report(payload, filled, rows)

    if arguments.check:
        if not OUTPUT.exists() or OUTPUT.read_bytes() != payload:
            print(f"{OUTPUT} is out of date", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is up to date ({filled} cells)")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_bytes(payload)
    REPORT.write_text(report, encoding="ascii")
    print(f"{OUTPUT}: {len(payload)} bytes, {filled} cells mapped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
